[project]
name = "erc-query"
authors = ["erc-query-dev"]
description = "A Clarity smart contract for asset query and management"
telemetry = false
requirements = []
[contracts.asset-query]
path = "contracts/asset-query.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
